FROM node:18-alpine

# Instalar Python3 y pip, luego instalar aioesphomeapi
RUN apk add --no-cache python3 py3-pip && \
    pip3 install --no-cache-dir aioesphomeapi

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

EXPOSE 3001

CMD ["npm", "run", "dev"]