FROM node:18-alpine AS base

# Instalar Python3 y pip, luego instalar aioesphomeapi
RUN apk add --no-cache python3 py3-pip && \
    pip3 install --no-cache-dir aioesphomeapi

WORKDIR /app

COPY package*.json ./
ENV NODE_ENV=production
RUN npm install --production && npm cache clean --force

COPY . .

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nodejs -u 1001

USER nodejs

EXPOSE 3001

CMD ["npm", "start"]