FROM node:18-alpine AS base

WORKDIR /app

COPY package*.json ./
ENV NODE_ENV=production
RUN npm install --production && npm cache clean --force

COPY . .

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nodejs -u 1001

USER nodejs

EXPOSE 3001

CMD ["npm", "run", "start:prod"]